### ISSUE TITLE
Error while loading model

### ISSUE THREAD

**Issue by anshumanvenkatesh** [thekevinscott/ml-classifier#5]
Getting a ```Cannot read property 'sourceLayer' of undefined``` while trying to load pre-trained model (both 'mobilenet_v1_0.25_224' and 'mobilenet_v1_1.0_224'.

Tried with both tf-js v0.12.2 and latest v0.15.3

**Comment by thekevinscott** [comment]
Can you push your code to a repo, or provide a code sandbox link?

**Comment by anshumanvenkatesh** [comment]
https://jsfiddle.net/2Ltwr9z4/

Thank you.

**Comment by thekevinscott** [comment]
https://jsfiddle.net/0ecu49aL/

`output` should be `outputs`:

```
    return tf.model({
      inputs: [model.inputs[0]],
      outputs: lastLayer.output
    })
```
